# Makefile for uClibc
#
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC := __syscall_error.c

SSRC := __longjmp.S  _setjmp.S  clone.S  crt1.S  setjmp.S  vfork.S
